services:
  order_db:
    image: mysql:8
    container_name: order_db
    restart: always
    environment:
      MYSQL_DATABASE: order_service_db
      MYSQL_ROOT_PASSWORD: supersecret111
    ports:
      - "3309:3306"
    networks:
      - ecommerce_net
    volumes:
      - order_db_data:/var/lib/mysql

  order_service:
    build: .
    container_name: order_service
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - order_db
    networks:
      - ecommerce_net
    volumes:
      - .:/app

volumes:
  order_db_data:

networks:
  ecommerce_net:
    external: true
