
services:
  # ------------------------
  # MySQL Database (Product Service)
  # ------------------------
  product_db:
    image: mysql:8
    container_name: product_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    networks:
      - ecommerce_net
    volumes:
      - product_db_data:/var/lib/mysql

  # ------------------------
  # Product Service API (Django)
  # ------------------------
  product_service:
    build: .
    container_name: product_service
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - product_db
    networks:
      - ecommerce_net
    volumes:
      - .:/app
    command: uvicorn product_service.asgi:application --host 0.0.0.0 --port 8000

  # ------------------------
  # Product Service Consumer (RabbitMQ)
  # ------------------------
  product_consumer:
    build: .
    container_name: product_consumer
    env_file:
      - .env
    depends_on:
      - product_db
      - product_service
    networks:
      - ecommerce_net
    volumes:
      - .:/app
    command: python apps/products/consumer.py

volumes:
  product_db_data:

networks:
  ecommerce_net:
    external: true
