# Generated by Django 5.2.6 on 2025-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
